[versions]

agp = "9.0.0"
buildTools = "36.0.0"
compileSdk = "36"
kotlin = "2.3.0"
minSdk = "23"
targetSdk = "36"

androidx-appcompat = "1.7.1"
androidx-core-ctx = "1.17.0"
androidx-constraintLayout = "2.2.1"
androidx-fragment-ktx = "1.8.9"
androidx-navigation = "2.9.6"

kotlinx-datetime = "0.7.1-0.6.x-compat"
kotlinx-serialization = "1.10.0"

coil = "2.7.0"
koin = "4.1.1"
material = "1.13.0"
okhttp = "4.12.0"
retrofit = "3.0.0"
retrofit-kotlinx-serialization = "1.0.0"

junit = "4.13.2"

[libraries]

kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin" }

androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "androidx-appcompat"}
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "androidx-core-ctx"}
androidx-constraintLayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "androidx-constraintLayout"}
androidx-fragment-ktx = { module = "androidx.fragment:fragment-ktx", version.ref = "androidx-fragment-ktx"}
androidx-navigation-fragment-ktx = { module = "androidx.navigation:navigation-fragment-ktx", version.ref = "androidx-navigation"}
androidx-navigation-safeArgs = { module = "androidx.navigation:navigation-safe-args-gradle-plugin", version.ref = "androidx-navigation"}
androidx-navigation-ui-ktx = { module = "androidx.navigation:navigation-ui-ktx", version.ref = "androidx-navigation"}
coil = { module = "io.coil-kt:coil", version.ref = "coil"}
coil-svg = { module = "io.coil-kt:coil-svg", version.ref = "coil"}
junit = { module = "junit:junit", version.ref = "junit" }
koin-android = { module = "io.insert-koin:koin-android", version.ref = "koin"}
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinx-datetime"}
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization"}
material = { module = "com.google.android.material:material", version.ref = "material"}
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit"}
retrofit-kotlinx-serialization = { module = "com.jakewharton.retrofit:retrofit2-kotlinx-serialization-converter", version.ref = "retrofit-kotlinx-serialization"}

[plugins]

android-application = { id = "com.android.application", version.ref = "agp" }
android-legacyKapt = { id = "com.android.legacy-kapt", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
